"""Initial revision

Revision ID: 2de749b43bef
Revises: 3f54e57ea07c
Create Date: 2026-03-21 23:58:26.188378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de749b43bef'
down_revision: Union[str, Sequence[str], None] = '3f54e57ea07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('img_background', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'img_background')
    # ### end Alembic commands ###
