"""Initial revision

Revision ID: 38945084c9d7
Revises: 9fd322cfab6f
Create Date: 2026-05-09 13:46:32.315314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38945084c9d7'
down_revision: Union[str, Sequence[str], None] = '9fd322cfab6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_computer_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_zone_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_club_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'computers', ['computer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
    op.add_column('computers', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('computers', sa.Column('y', sa.Float(), nullable=True))
    op.drop_constraint(op.f('computers_zone_id_fkey'), 'computers', type_='foreignkey')
    op.create_foreign_key(None, 'computers', 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('zones_club_id_fkey'), 'zones', type_='foreignkey')
    op.create_foreign_key(None, 'zones', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zones', type_='foreignkey')
    op.create_foreign_key(op.f('zones_club_id_fkey'), 'zones', 'clubs', ['club_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'computers', type_='foreignkey')
    op.create_foreign_key(op.f('computers_zone_id_fkey'), 'computers', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    op.drop_column('computers', 'y')
    op.drop_column('computers', 'x')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_club_id_fkey'), 'bookings', 'clubs', ['club_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('bookings_zone_id_fkey'), 'bookings', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('bookings_computer_id_fkey'), 'bookings', 'computers', ['computer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
