"""Initial revision

Revision ID: 3f54e57ea07c
Revises: 7ac8d26ec1c4
Create Date: 2026-03-21 23:04:07.674942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f54e57ea07c'
down_revision: Union[str, Sequence[str], None] = '7ac8d26ec1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'computer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'zone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clubs', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clubs', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('computers', 'zone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('zones', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zones', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('computers', 'zone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clubs', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clubs', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'zone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'computer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
