"""Initial revision

Revision ID: 724acdfb4ff9
Revises: 7d7914a72327
Create Date: 2026-03-21 12:31:18.405589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724acdfb4ff9'
down_revision: Union[str, Sequence[str], None] = '7d7914a72327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('image_price_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'image_price_url')
    # ### end Alembic commands ###
