"""Initial revision

Revision ID: 7ac8d26ec1c4
Revises: f39e13e50f7e
Create Date: 2026-03-21 22:55:27.923628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac8d26ec1c4'
down_revision: Union[str, Sequence[str], None] = 'f39e13e50f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_computer_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_zone_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_club_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bookings', 'clubs', ['club_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bookings', 'computers', ['computer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('clubs_city_id_fkey'), 'clubs', type_='foreignkey')
    op.drop_constraint(op.f('clubs_owner_id_fkey'), 'clubs', type_='foreignkey')
    op.create_foreign_key(None, 'clubs', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'clubs', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('computers_zone_id_fkey'), 'computers', type_='foreignkey')
    op.create_foreign_key(None, 'computers', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('zones_club_id_fkey'), 'zones', type_='foreignkey')
    op.create_foreign_key(None, 'zones', 'clubs', ['club_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zones', type_='foreignkey')
    op.create_foreign_key(op.f('zones_club_id_fkey'), 'zones', 'clubs', ['club_id'], ['id'])
    op.drop_constraint(None, 'computers', type_='foreignkey')
    op.create_foreign_key(op.f('computers_zone_id_fkey'), 'computers', 'zones', ['zone_id'], ['id'])
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.create_foreign_key(op.f('clubs_owner_id_fkey'), 'clubs', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('clubs_city_id_fkey'), 'clubs', 'cities', ['city_id'], ['id'])
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_club_id_fkey'), 'bookings', 'clubs', ['club_id'], ['id'])
    op.create_foreign_key(op.f('bookings_zone_id_fkey'), 'bookings', 'zones', ['zone_id'], ['id'])
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('bookings_computer_id_fkey'), 'bookings', 'computers', ['computer_id'], ['id'])
    # ### end Alembic commands ###
