"""Initial revision

Revision ID: 96e79a3730ec
Revises: 6f53d65e1b91
Create Date: 2026-03-19 13:29:31.592538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96e79a3730ec'
down_revision: Union[str, Sequence[str], None] = '6f53d65e1b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('zone_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('club_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'zones', ['zone_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'clubs', ['club_id'], ['id'])
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', postgresql.ENUM('free', 'booked', 'not_available', name='status'), server_default=sa.text("'free'::status"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'club_id')
    op.drop_column('bookings', 'zone_id')
    # ### end Alembic commands ###
