"""Initial revision

Revision ID: bfac3a4995ed
Revises: d62f12d272d1
Create Date: 2026-03-19 18:42:09.323655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfac3a4995ed'
down_revision: Union[str, Sequence[str], None] = 'd62f12d272d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('cities', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'clubs', ['address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clubs', type_='unique')
    op.drop_column('cities', 'longitude')
    op.drop_column('cities', 'latitude')
    # ### end Alembic commands ###
