"""Initial revision

Revision ID: d403fd465b73
Revises: 38945084c9d7
Create Date: 2026-05-09 13:54:06.906123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd403fd465b73'
down_revision: Union[str, Sequence[str], None] = '38945084c9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('zones', sa.Column('y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'y')
    op.drop_column('zones', 'x')
    # ### end Alembic commands ###
