"""Initial revision

Revision ID: d62f12d272d1
Revises: 96e79a3730ec
Create Date: 2026-03-19 13:44:12.324562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62f12d272d1'
down_revision: Union[str, Sequence[str], None] = '96e79a3730ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('clubs', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'longitude')
    op.drop_column('clubs', 'latitude')
    # ### end Alembic commands ###
