"""Initial revision

Revision ID: ee8cfa5dda03
Revises: bfac3a4995ed
Create Date: 2026-03-21 00:40:30.483840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8cfa5dda03'
down_revision: Union[str, Sequence[str], None] = 'bfac3a4995ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('users_city_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.add_column('zones', sa.Column('cpu', sa.String(), nullable=True))
    op.add_column('zones', sa.Column('gpu', sa.String(), nullable=True))
    op.add_column('zones', sa.Column('ram', sa.String(), nullable=True))
    op.add_column('zones', sa.Column('ssd', sa.String(), nullable=True))
    op.add_column('zones', sa.Column('monitor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'monitor')
    op.drop_column('zones', 'ssd')
    op.drop_column('zones', 'ram')
    op.drop_column('zones', 'gpu')
    op.drop_column('zones', 'cpu')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_city_id_fkey'), 'users', 'cities', ['city_id'], ['id'])
    op.alter_column('users', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
